
name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-llvm-cov
        continue-on-error: true
        uses: taiki-e/install-action@cargo-llvm-cov
          
      - run: cargo llvm-cov --ignore-filename-regex '.*(persister|event_emitter|stats_api|settings_manager|local_player_store|register_listeners|test_utils|background_worker|event_listener|file_system|packet_sniffer|region_store|flags|start|register_listeners|heartbeat_api|lost-metrics-core|lost-metrics-data|lost-metrics-misc|lost-metrics-store|lost-metrics-sniffer-stub).*' --lcov --output-path lcov.info

      - uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./lcov.info
